# Generated by Django 4.0.2 on 2022-02-17 17:07

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('PollZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='opinion_list',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:,(-)?\\d+)*\\Z'), code='invalid', message=None)], verbose_name='Meinung'),
        ),
    ]
